const EXT_TO_LANG: Record<string, string> = {
  rs: "rust",
  ts: "typescript",
  tsx: "tsx",
  js: "javascript",
  jsx: "jsx",
  py: "python",
  rb: "ruby",
  go: "go",
  java: "java",
  kt: "kotlin",
  c: "c",
  h: "c",
  cpp: "cpp",
  hpp: "cpp",
  cs: "csharp",
  swift: "swift",
  zig: "zig",
  lua: "lua",
  sh: "shell",
  bash: "shell",
  zsh: "shell",
  fish: "shell",
  ps1: "powershell",
  html: "html",
  htm: "html",
  css: "css",
  scss: "scss",
  less: "less",
  json: "json",
  yaml: "yaml",
  yml: "yaml",
  toml: "toml",
  xml: "xml",
  svg: "xml",
  md: "markdown",
  mdx: "mdx",
  sql: "sql",
  graphql: "graphql",
  gql: "graphql",
  dockerfile: "dockerfile",
  docker: "dockerfile",
  nix: "nix",
  clj: "clojure",
  cljs: "clojure",
  cljc: "clojure",
  edn: "clojure",
  ex: "elixir",
  exs: "elixir",
  erl: "erlang",
  hs: "haskell",
  ml: "ocaml",
  mli: "ocaml",
  r: "r",
  R: "r",
  php: "php",
  pl: "perl",
  tf: "hcl",
  proto: "proto",
  makefile: "makefile",
  cmake: "cmake",
  ini: "ini",
  conf: "ini",
  diff: "diff",
  patch: "diff",
} as const;

export function getLang(filePath: string): string | undefined {
  const name = filePath.split("/").pop() ?? "";
  const lower = name.toLowerCase();
  if (lower === "makefile" || lower === "gnumakefile") return "makefile";
  if (lower === "dockerfile") return "dockerfile";
  if (lower === "cmakelists.txt") return "cmake";
  const ext = name.includes(".") ? name.split(".").pop()! : "";
  return EXT_TO_LANG[ext];
}
